<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>rf0003demo</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="agent.Files">
      <HintPath>/home/agentuser/AgentFramework/src/agent.files/bin/Release/net10.0/agent.Files.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
