<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../agent/agent.csproj" />
    <ProjectReference Include="../agent.core/agent.core.csproj" />
    <ProjectReference Include="../agent.rag/agent.rag.csproj" />
    <ProjectReference Include="../agent.planner/agent.planner.csproj" />
    <ProjectReference Include="../agent.codegen/agent.codegen.csproj" />
    <ProjectReference Include="../agent.vectormemory/agent.vectormemory.csproj" />
    <ProjectReference Include="../agent.workspace/agent.workspace.csproj" />
    <ProjectReference Include="../agent.recovery/agent.recovery.csproj" />
    <ProjectReference Include="..\agent.output\agent.output.csproj" />
  </ItemGroup>

</Project>
